### ISSUE TITLE
Create Server Routes

### ISSUE THREAD

**Issue by Svtucci** [OCDDiva/OCDDiva-project#6]

**Comment by mineralsun** [comment]
Is this like on App.jsx? if so I did that today and we can close this. If this is about like server side routes than we can leave it open! :)

**Comment by Svtucci** [comment]
Hey just saw this! Ah it was a general server routes issue. We can split it into 2 instead, 1 for the app.jsx that you already did, and close it and then create another one for the server side routes. We can talk over it tonight during classwork
